name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login into crates.io
      run: cargo login ${{ secrets.CRATES_IO }}
    - name: Build binaries in "release" mode
      run: cargo build -r
    - name: "Publish to crates.io"
      run: cargo publish # publishes your crate as a library that can be added as a dependency
